### ISSUE TITLE
[Question] Community Participation & PR Expectations?

### ISSUE THREAD

**Issue by aphix** [jaku/SnapCameraPreservation#1]
Hey @jaku, found your repo thanks to Nutty's recent video (https://www.youtube.com/watch?v=UU8Jq6It8o4) and have a question regarding community participation:

**Do you want us to submit PRs with cached data[1], lens names/urls, or anything of the sort?**

Perhaps it would be easiest to have a "requests" file where people can add their own URLs to lenses they like? Maybe just a single-line-per-URL text file?

[1] One question re: caches, I don't know if there's any personal or hardware-specific data contained in them. If so, then it might be worth finding a way to scrub it before submission, being that the raw data from the lens is arguably more useful than even a URL.

_A related final thought after typing this:_

The URLs to download the filters will still _probably_ work after snap camera shuts down since snapchat itself isn't going down, and I doubt they store it in more than one location. That said, there's no way to know until after Jan 25th. It's possible there's a header/UA string that the mobile app sends differently from the desktop app they could use to gatekeep it after the shutdown.

Cheers; love the idea. Let us know how we can help out.

**Comment by jaku** [comment]
Hey Aphix,

No need to submit PRs with cached data. The modified client I have automatically does that so as long as you're using that (which I'll post here soon). As long as you activate each lens once it should cache them.

I'll work on a way to verify this as well. I've sadly been sick all week. :|

And I agree, I think a lot of stuff will actually still work after the shutdown but we're not completely sure. The desktop app does send some headers that are required for the files but from what I could tell the mobile app hits a different endpoint. Again, might all still work for some things but hard to know 100% until the shutdown.

**Comment by jaku** [comment]
Created a quick patch site that will patch the exe instead of hosting the EXE directly. But that is now available along with the BPS file if people want to manually patch using another tool.

**Comment by MissCurlyBlonde** [comment]
Hey Jaku, thx for getting involved.

Q1 - What if down the line we need to reinstall SnapCam due to a windows reinstall or whatever? Do we follow the patching method ?
Q2 - The firewall blocking method in Nutty's vid, is that legit? As in, if we do that, and we backed up our files/installs/lenses/cache on our hard drives, it will work 100% regardless of what SnapInc. decides in the future?
Q3 - If the answer to Q2 is NO, is there a way we can make our own hosting servers, and with your help, repatching SnapCam to work with that, and if yes, do we need to hurry till the 25'th to get it up & running so we can downloaded our fav lenses?

**Comment by CybaGirl** [comment]
Q2 - The firewall blocking method in Nutty's vid, is that legit? As in, if we do that, and we backed up our files/installs/lenses/cache on our hard drives, it will work 100% regardless of what SnapInc. decides in the future? 
 
 I made a pose on Nutty's video about blocking the IP address that Snap Chat phones home to. But for some reason he must of deleted it? I have noticed he is a bit like that at times?
 
 Anyway. Blocking the IP address at the host file is much safer than using a firewall in my experience of (thirty years running my own computer business) simply because some firewalls even if the program is blocked still allows programs to phone home. Plus if the firewall gets turned off for some reason then the program in question can phone home.
 
 But blocking the IP through host file will always stop the program from calling home. I have used this method for many years and never had an issue with blocking any program that calls home. Plus if my Firewall is turned off for one reason or another. The program still cannot phone home as it it blocked in the host file.
 
 So again much better than using a firewall.
 
 If you want to know how to do this. Just let me know as it's very simple and you can use any free Host Editor or even Notepad if you wish. Here is a screenshot of how I did it using the Host Editor that I use.
 
 https://prnt.sc/Cia03FWHhxjF
 
 Also the IP address was found using my firewall program as shown in this screenshot.
 
 https://prnt.sc/hudXRVefcQfw
 
 Any questions just let me know.

**Comment by CybaGirl** [comment]
> Q2 - The firewall blocking method in Nutty's vid, is that legit? As in, if we do that, and we backed up our files/installs/lenses/cache on our hard drives, it will work 100% regardless of what SnapInc. decides in the future? 

 
 I made a post on Nutty's video about blocking the IP address that Snap Chat phones home to. But for some reason he must of deleted it?
 
 Anyway. Blocking the IP address at the host file is much safer than using a firewall in my experience of (thirty years running my own computer business) simply because some firewalls even if the program is blocked still allows programs to phone home. Plus if the firewall gets turned off for some reason then the program in question can phone home.
 
 But blocking the IP through host file will always stop the program from calling home. I have used this method for many years and never had an issue with blocking any program that calls home. Plus if my Firewall is turned off for one reason or another. The program still cannot phone home as it it blocked in the host file.
 
 So again much better than using a firewall.
 
 If you want to know how to do this. Just let me know as it's very simple and you can use any free Host Editor or even Notepad if you wish. Here is a screenshot of how I did it using the Host Editor that I use.
 
 https://prnt.sc/Cia03FWHhxjF
 
 Also the IP address was found using my firewall program as shown in this screenshot.
 
 https://prnt.sc/hudXRVefcQfw
 
 Any questions just let me know.

**Comment by MissCurlyBlonde** [comment]
That IP address is universal? I can just put that in my hosts file and it'll work blocking the program ? Or it's a dynamic one?

**Comment by CybaGirl** [comment]
> That IP address is universal? I can just put that in my hosts file and it'll work blocking the program ? Or it's a dynamic one?

Hello, and thank you for your comment.

Most companies use static IP addresses so you should be ok. The only time this would not work is if they changed servers. But this rarely happens in my experience.

I have added many IP's in my host list over the years and never had an issue.

Hope this helps :).

**Comment by jaku** [comment]
> Hey Jaku, thx for getting involved.
> 
> Q1 - What if down the line we need to reinstall SnapCam due to a windows reinstall or whatever? Do we follow the patching method ? Q2 - The firewall blocking method in Nutty's vid, is that legit? As in, if we do that, and we backed up our files/installs/lenses/cache on our hard drives, it will work 100% regardless of what SnapInc. decides in the future? Q3 - If the answer to Q2 is NO, is there a way we can make our own hosting servers, and with your help, repatching SnapCam to work with that, and if yes, do we need to hurry till the 25'th to get it up & running so we can downloaded our fav lenses?

Q1) Yes, you just need to install the version of Snap Chat and then patch it again. My servers will still be up, it costs me almost nothing to host and I have projects that I've been running for other things that have gone well past 10 years now. 

Q2) Blocking is a solution for sure, he showed the downsides to them but it should work. We really don't 100% know though if it will continue to last as maybe the cache still expires after a set time.

Q3) That is what this repo is supposed to have hopefully next week so that others can just run and host their own server. Instructions on how to manually patch your own exe and run the same code that I've created so you don't have to go through my server.

**Comment by MissCurlyBlonde** [comment]
Done & done. 
Thank you, I appreciate it.

**Comment by CybaGirl** [comment]
> 
> I don't think this is a good idea. Blocking an IP when it's on a cloud provider can cause issues with other hosts or services by the same company that might be on the same IP. That IP you posted is not static, pinging snapcamera.snapchat.com on my computer and a server are giving two different IPs already from your post. https://imgur.com/a/LfVsZRy
>

Thank you for the extra clarification and I stand corrected :).  I guess I should have pinged snap camera. But I don't use snap chat or any other services they offer. So I just relied on my firewall for telling me the IP address(s).

> 
> You can still 100% just block the host snapcamera.snapchat.com in the hosts file. Adding it as 0.0.0.0 snapcamera.snapchat.com
> 
> Would do the job and if they changed IPs it would not matter. Also there is 2 another domains they use called studio-app.snapchat.com and studio-crash.snapchat.com which sends some information up to them when you open and or crash the app. So blocking that might be a good idea too.
>

Ok thanks will do just in case :).

**Comment by jaku** [comment]
> > I don't think this is a good idea. Blocking an IP when it's on a cloud provider can cause issues with other hosts or services by the same company that might be on the same IP. That IP you posted is not static, pinging snapcamera.snapchat.com on my computer and a server are giving two different IPs already from your post. https://imgur.com/a/LfVsZRy
> 
> Thank you for the extra clarification and I stand corrected :). I guess I should have pinged snap camera. But I don't use snap chat or any other services they offer. So I just relied on my firewall for telling me the IP address(s).
> 
> > You can still 100% just block the host snapcamera.snapchat.com in the hosts file. Adding it as 0.0.0.0 snapcamera.snapchat.com
> 
> But won't that block the website itself?
> 
> > Would do the job and if they changed IPs it would not matter. Also there is 2 another domains they use called studio-app.snapchat.com and studio-crash.snapchat.com which sends some information up to them when you open and or crash the app. So blocking that might be a good idea too.
> 
> Ok thanks will do just in case :).

I've only seen the app user the studio-app.snapchat.com domain and not snapcamera.snapchat.com. It's true the website is hosted on snapcamera.snapchat.com and putting in 0.0.0.0 for the IP will prevent you from accessing the site as well. But if you have everything downloaded you don't really need to access it anymore anyways.
