### ISSUE TITLE
Setting up the server, but not using AWS or S3

### ISSUE THREAD

**Issue by Kimberly-McBlaze** [jaku/SnapCameraPreservation#16]
Hi. I'd like to set up the snap camera server on my own machine instead of using AWS or S3, is that possible?

**Comment by jaku** [comment]
Sure, but would require code changes that you'd have to make yourself in both the snap camera program and the server itself.

**Comment by MiaRose** [comment]
I would also be interested with that as well.

**Comment by Kimberly-McBlaze** [comment]
> Sure, but would require code changes that you'd have to make yourself in both the snap camera program and the server itself.

Got'cha... is there anything out there that I could host myself that uses the S3 protocol / emulates AWS?

**Comment by jaku** [comment]
https://github.com/jamhall/s3rver appears to do just that.

**Comment by jaku** [comment]
It should be noted that S3 isn't even required at this point, any setup that just serves files over HTTP/HTTPS can work now.

When the repo started we needed to download the lenses somewhere and I picked S3. So while we have code to upload to S3, the serving of files is just done over HTTPS. 

Setting up an nginx server locally and hosting the files from the torrent shared on my Twitter would get you what you need for most of it. 

However, I do have an idea of how to make a local application for users so that it doesn't require a similar setup as this server and would be simpler for others to set up. I'm going on vacation starting today but I have a lot of time on some planes so I'll see if I can't get something started and shared.

**Comment by jaku** [comment]
Initial attempts at this are looking good. The way I plan to make it work is the following.

It will be an electron application so that it can easily run on Windows and macOS. I'm currently calling it Lens Focal. It will have options to auto-patch the Snap Camera to use the local server or mine.

No lenses will be stored with it, instead when you search in the snap camera app with the local patch applied it will communicate with Lens Focal, which will then reach out to my server to get the required lens files. It will download the needed files locally in an area that can be shared/opened/etc. 

When opening Snap Camera, Lens Focal will respond with whatever lens data is currently stored in the above-mentioned folders. So users can drop in files from other users if need be.

I've already got a good amount of this working in a very hacky prototype way. I'll see how much I can get done during my flights, but no promises on anything major getting done until after I get back on the 8th.

**Comment by Jhon17757** [comment]
Hello, can anyone upload a video tutorial of how to do it? It would be very helpful thanks.

**Comment by Kimberly-McBlaze** [comment]
This is awesome news! Thanks so much for all you do. We'll see how this goes. Take all the time you need.

**Comment by jaku** [comment]
> Hello, can anyone upload a video tutorial of how to do it? It would be very helpful thanks.

No, because this hasn't been built yet. So no video. You can watch this video if you're asking about how to patch the application to use my server for now. https://www.youtube.com/watch?v=K1z2Qy3LXsU

@Kimberly-McBlaze thanks. I'll continue with the project when I'm back home next week.

**Comment by kjetil-gdm** [comment]
Hello. Great work on this, jaku. Would this Lens Focal server enable us to add previously cached lenses from the snap camera cache folders?

**Comment by jaku** [comment]
In theory yes. 

I've managed to get missing lenses working but not in a very clear, easy way. It's very messy at this point but I think with having this application installed I'll be able to have it automatically do all the necessary steps to get them working.
