### ISSUE TITLE
Filters not working anymore

### ISSUE THREAD

**Issue by inMelodyy** [jaku/SnapCameraPreservation#17]
They just arent loading at all

**Comment by Vladykus** [comment]
I am having the same problem, but is due to the problems with version 1.20-1.21 (in 1.19 everything works fine). But right now after updating to newer version and doing everything as it sais in the instructions, problem returned and version 1.21 not activating filters as it was before with 1.20 and because of that I was using version 1.19.

I have launched version 1.21, downloaded all filters (lences) into cache folder, they are showing in the list with images, but they not working, at the same time when launching older version 1.19 they are working, but showing in the list without images (according to the no connection to the server).

I tryied reinstalling the programm few times, reinstalled Microsoft Visual C++ all versions, but can't understand why version 1.20-1.21 not activating lenses.

Could you please help figguring out why filters (lences) work in 1.19, but not work in 1.21? Or maybe help me connect my version 1.19 of exe file with your server?

Looking forward to hearing from you. Thank you!

**Comment by jaku** [comment]
See this issue and report location and speeds on the 2 files posted in my comments. 

https://github.com/jaku/SnapCameraPreservation/issues/12

**Comment by Vladykus** [comment]
> See this issue and report location and speeds on the 2 files posted in my comments.
> 
> #12

No problem with download of your file [https://s3.ap-southeast-1.amazonaws.com/asia-lens-storage-reversesnapcht.jaku.tv/24d8c52a168e4ba68369eea4f4bbbe3b], instant download to me. Filters download fine, but not work on 1.21 version, on 1.19 version work fine, but with black preview and without patched connection to new server. I have tryied many variants, but it's some kind of problem inside newer version of the program.

**Comment by jaku** [comment]
Do only the lenses with images work? It looks like this is an issue with some types of lenses that were backed up.

**Comment by Vladykus** [comment]
> Do only the lenses with images work? It looks like this is an issue with some types of lenses that were backed up.

No, None of the lenses work in 1.21, in my case newer versions then 1.19 not showing lenses. I have reinstalled all versions of Microsoft Visual C++ (Microsoft Visual C++ 2015-2022 installing with the program), but can't understand why on 1.19 lenses work, but on 1.20-1.21 don't. What can it be? I have tryied to split .exe file between 1.19 and patched 1.21, but nothing changed. As I understand it's some kind of updated in newer version that not work on my PC and it is inside .exe file, that is why need to find out solution how to use lenses in 1.21 or find out how to patch 1.19.

**Comment by jaku** [comment]
I can make a patch for 1.19 and see if it works for you. I'll try to make it tonight. But it's odd it works for so many others. I think there may be other factors at play.

**Comment by jaku** [comment]
@Vladykus I've made a patch for 1.19, it's on the patching site. Please try it out and let me know if it's working for you with the patch on that verison.

**Comment by Vladykus** [comment]
> @Vladykus I've made a patch for 1.19, it's on the patching site. Please try it out and let me know if it's working for you with the patch on that verison.

OMG it works! Everything works as it was before Snap Inc. shut down the Snap Camera - filters (lenses), cache preview, shop preview, everything download within a few seconds.

Thank you very much, if you need further test, please let me know.

**patched version 1.19**
![2023-02-03_162757](https://user-images.githubusercontent.com/124179227/216628202-f15fd4fd-31e0-4fba-92b8-cf4af777af8d.jpg)

**Comment by jaku** [comment]
Thanks. I'll suggest to others having similar issues to try 1.19.
