### ISSUE TITLE
[Thought] Seems the web is exposing some lenses

### ISSUE THREAD

**Issue by ctsstc** [jaku/SnapCameraPreservation#30]
It seems you can search them, but not all of them have "try lens" on the web.
https://lens.snapchat.com/924f374625604452a5d1273dad9d9726

I'm not sure if this is the endpoint you'd need that it fetches from that page after clicking the "try lens"
https://api-kit.snapchat.com/com.snap.camerakit.v3.Lenses/groups/5823ca90-5e1a-44b4-a007-644cab5c6e64/lenses/59752180963
You cannot directly navigate there as there are authentication headers that are required.

It returns something like the following; I imagine the `lnsUrl` is the filter?
https://bolt-gcdn.sc-cdn.net/3/4TrFy6k6nrG8zHOWHNtwY?bo=EhgaABoAMgF9OgEEQgYIw73ZmgZIAlASYAE%3D&uc=18

Ultimately it seems like they're still figuring out their rough web launch as not all lenses have the Try Lens on the web, and the current snap web seems to only have a small subset of lenses if I'm seeing it correctly?

```json
{
  "lens": {
    "id": "59752180963",
    "name": "Crying",
    "vendorData": {},
    "content": {
      "lnsUrl": "https://bolt-gcdn.sc-cdn.net/3/4TrFy6k6nrG8zHOWHNtwY?bo=EhgaABoAMgF9OgEEQgYIw73ZmgZIAlASYAE%3D&uc=18",
      "lnsSha256": "27DF4AF94CFDEACA8FC6FAF5E76E419FB9DDA6C6D64800691DAEA10E022BC12E",
      "iconUrl": "https://cf-st.sc-cdn.net/aps/bolt/aHR0cHM6Ly9ib2x0LWdjZG4uc2MtY2RuLm5ldC8zL0dTbEg0ZVk0aFBuc01MbEYwUGNaOD9ibz1FaGdhQUJvQU1nRjlPZ0VFUWdZSXc3M1ptZ1pJQWxBU1lBRSUzRCZ1Yz0xOA._FMpng",
      "preview": {
        "imageUrl": "https://lens-preview-storage.storage.googleapis.com/previewmedia/preview_thumbnail/2237191d-e6df-432b-b222-cb9a4bceed2c_360_640.webp"
      },
      "assetManifest": [
        {
          "type": "DEVICE_DEPENDENT_ASSET_UNSET",
          "id": "LENSCORE_DEFAULT_RETOUCH_ASSET",
          "requestTiming": "REQUIRED",
          "assetUrl": "",
          "assetChecksum": ""
        },
        {
          "type": "DEVICE_DEPENDENT_ASSET_UNSET",
          "id": "LENSCORE_CAMEO_STATIC_EMOTION_CRYING_WEAKER",
          "requestTiming": "REQUIRED",
          "assetUrl": "",
          "assetChecksum": ""
        }
      ],
      "defaultHintId": "UNKNOWN_LENS_HINT",
      "hintTranslations": {},
      "lnsUrlBolt": "https://bolt-gcdn.sc-cdn.net/3/4TrFy6k6nrG8zHOWHNtwY?bo=EhgaABoAMgF9OgEEQgYIw73ZmgZIAlASYAE%3D&uc=18",
      "iconUrlBolt": "https://bolt-gcdn.sc-cdn.net/3/GSlH4eY4hPnsMLlF0PcZ8?bo=EhgaABoAMgF9OgEEQgYIw73ZmgZIAlASYAE%3D&uc=18"
    },
    "isThirdParty": false,
    "cameraFacingPreference": "CAMERA_FACING_UNSET",
    "featureMetadata": [],
    "lensCreator": { "displayName": "Snapchat" }
  }
}
```

**Comment by jaku** [comment]
I've already explored this option. That same data can be gotten directly from the page without trying the lens by checking the source as well, there is a JSON object inside a <script> tag that contains it.

The issue with this data is that they are providing a .lns file directly, which can still be useful and is something I'm attempting with the Lens Focal application I'm working on.

The process for Snap Camera to add lenses would normally get the information from https://studio-app.snapchat.com/vc/v1/explorer/unlock?uid=${lensID} endpoint. Specifically the lens_url object. Inside that same response would be a signature. From what I can tell that signature isn't of the zip file, but of the .lns file it is converted to.

Example Zip: https://s3.amazonaws.com/lens-storage-reversesnapcht.jaku.tv/f30b133010d54f4880ed162d3539fba2
Signature: MGYCMQDBLz5dVtyKMI7aWgFWiMRm72KpxWUteDHsdLtzYwkhwiBqhTd6BryNAtjWRA+tO84CMQCyYqlI84CL6Gha/vC/0zJgDIOrK3KY4ru3gOnMN4uvpELOUL9m3LG97kAEyJImYyc=

I've decoded the .lns file enough to be able to convert it back to a .zip file but it's not perfectly a 1:1 copy of the original zip, so when giving Snap Camera the data it needs to download my converted .zip file the signature check fails. https://twitter.com/Jaku/status/1622977008895672322 is when I initially got this figured out, but I've been busy and also did hit the next few hurdles.

Patching out the initial .zip signature check does allow things to go further, but then there is another check that I haven't been able to completely patch out for some reason, as the .lns file is then checked again every time you load it. Interestingly enough if I create the folder for the .lns file and make it read-only, the lens will load even with the failed signature check due to some of the patching I was able to do.

I'm not a fan of the patching solution for the application, but it may be the only way to get it working without lots of workarounds. Unless we can figure out how the signature is generated which I suspect is a public/private key signing process that we'd have no real insight into, patching seems like the only real possibility here.

**Comment by ctsstc** [comment]
I'm not sure if it's a red herring, but the signature looks like a base64 encode (since it ends in `=`), which would make sense being over the web in JSON, but decoding it looks like it's likely just some binary value, maybe this has offsets or signatures in it almost seems 🤷 

```
0f\x021\x00Á/>]VÜ\x8A0\x8EÚZ\x01V\x88Äfïb©Åe-x1ìt»sc\t!Â j\x857z\x06¼\x8D\x02ØÖD\x0F­;Î\x021\x00²b©Hó\x80\x8BèhZþð¿Ó2`\f\x83«+r\x98â»·\x80éÌ7\x8B¯¤BÎP¿fÜ±½î@\x04È\x92&c'
```

**Comment by jaku** [comment]
Yeah, my guess is that it's just the easy way to share it over JSON.

**Comment by natv** [comment]
Even once we get this working with their web version, is there a way to un-crop our body on the their webpage? (I used to use this for Zoom/Teams meetings when I was too lazy to put on real makeup, I had a developer create a custom make-up lens for me that looks similar to my real make-up)

Anyway, if the video isn't cropped to portrait shape, then the workaround for not having a Virtual Camera device is to use OBS to grab the webpage video in real-time and use it that way.  But again this wouldn't work well with the cropped body.
