### ISSUE TITLE
MacOS version doesn't show lens backups

### ISSUE THREAD

**Issue by dpkonofa** [jaku/SnapCameraPreservation#49]
I had to wipe my machine recently and re-installed SnapCamera from the installer I already had for v1.21.0. I was also able to restore the list of my favorite lenses from a Time Machine backup. None of the lenses load, though, even with the Certificate installed and set to Always Trust and the hosts file modified to that IP address. Is there anything else that needs to happen? Is that IP address still valid?

**Comment by jaku** [comment]
Install the 1.19 version on Mac.

**Comment by dpkonofa** [comment]
Will do. I’ll give that a shot and report back. Anywhere trustworthy you know of?

**Comment by curya** [comment]
![image](https://user-images.githubusercontent.com/71131343/235326308-974c1b18-782f-4a8c-8bc6-4a5e4dfa5a09.png)

I just installed 1.21.0 on Windows and I'm having the same issue. Should I also install 1.19?

**Comment by jaku** [comment]
No lenses show up under the jaku category. That is just there to indicate that you're on my server. You should have lenses under the categories and the search should work.

**Comment by jaku** [comment]
> Will do. I’ll give that a shot and report back. Anywhere trustworthy you know of?
> 
> Uptodown doesn't list a v1.19.0 for Mac - https://snap-camera.en.uptodown.com/mac/versions

https://snap-camera.en.uptodown.com/mac/download/4461816

1.18 should be fine too,

**Comment by dpkonofa** [comment]
No dice. 1.18 does the same.

<img width="141" alt="Screenshot 2023-05-03 at 9 41 51 AM" src="https://user-images.githubusercontent.com/6332378/235983771-71fba79d-401a-424d-9864-5633bd777d75.png">

**Comment by jaku** [comment]
Very strange, I've seen this issue before but it was either a regional thing or some later versions of the app not working for users. I'm not quite sure what else could be happening here.

**Comment by dpkonofa** [comment]
I'll try to roll back to an even older version and see if that helps at all. I'm not sure about the region thing. I'm in the US, if that helps.

**Comment by dpkonofa** [comment]
Tried again going down all the way to v1.14 and nothing seems to work. I'm not sure what else to try at this point.

**Comment by jaku** [comment]
Not quite sure, another user is reporting it works only once after rebooting. 

All we're doing is replacing the server it communicates with, and everything is still working on my test Mac.

I'd need to get access to a system having this issue to figure out what's different.

**Comment by dpkonofa** [comment]
Ok. Let me try it on another Mac and see if I can get it working there. The only thing I can think of is that somewhere our network is blocking access to the actual lenses on Snapchat's servers but I thought that they were all being accessed from your server instead.

If I can't get it to work on the other machine, I'll try a different network and report back. I'm not opposed to doing a screen share to help out and I'm happy to send you a donation if I can get this working again.

**Comment by dpkonofa** [comment]
Just reporting back in. Tried it on my Intel MacBook Pro and it works just fine and didn't even require a restart of the machine. M1 MacBook is still just spinning. The only difference between the 2 machines is that I had SnapCamera installed on the Intel machine prior to it coming down whereas the M1 machine is new and SnapCamera had to be installed.

**Comment by Angella-Mae** [comment]
Just to share and update, i also have mac but intell not m1/m2, i was able to download the 1.21 vs and patch. 

At first, NO lenses were showing at all just the spinning wheel of death.  I saw here that some had needed a restart, so i did that before trying to download any older versions, etc.  Upon doing so, the lenses now show up, and are able to be selected and favorited and the search bar does appear and allow me to type a search , ever the most generic of search words (e.g. office, makeup etc) No lenses are found.  

However, when i try to use any of them it has a black spinning wheel within the snapcode of the person who created it to the left of the video screen. (Where the lens that is in use usually is)

And it only shows 4 rows of lenses in the TOP COMMUNITY LENSES section, at the end of that has the blue spinning wheel. (that was originally all i saw at all prior to the restart. 

Any thoughts on what could be done next? Would an older version do anything? im thinking not so much, since i can see, select, favorite lenses now. the issue is whether any of the ones i try to select are actually being applied

**Comment by a-m1234** [comment]
Hello, i followed all the steps and still am not able to access the Jaku Bakup. Can someone send the proper link to the installation for snap camera. Also, do i have to clear the previous snap camera before i re-instal and try again
